# Site settings
title: Kim's Awesome Blog
email: blogitsecond@gmail.com
description: This is a blog about my whimsical life with my BFF - my Bubbie.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blogitsecond.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
